# Generated by Django 4.2.5 on 2024-01-05 17:19

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_note_search_vector'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='note',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title', 'content'], name='NewGinIndex'),
        ),
    ]
