# Generated by Django 4.2.5 on 2024-01-06 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_note_newginindex'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='note',
            name='NewGinIndex',
        ),
    ]
